---
title: "Probability Sampling Plots"
author: "Sabrina Xie"
date: "Last compiled `r format(Sys.time(), '%d %B, %Y, %X')`"
fig_width: 15
fig_height: 10
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE) 
```

```{r}

library(tidyverse)
library(huxtable)
library(ggplot2)
library(lubridate)
library(egg)
library(gridExtra)
library(spsurvey) #This code was written for spsurvey v5.0.0

```

```{r}

# retrieve raw data from database
setwd("~/OneDrive - New York State Office of Information Technology Services/Rscripts/Current")
source("new_database/Reading.LMAS.Data.R")
setwd("~/OneDrive - New York State Office of Information Technology Services/Rscripts/Probability.Sampling/")

rm(list=setdiff(ls(), c('newdata')))

#list relevant variables
lab<-newdata %>%
  filter(SAMPLE_DATE>'2020-01-01') %>%
  mutate(combined=paste(CHARACTERISTIC_NAME,
                        INFORMATION_TYPE,
                        RSLT_RESULT_SAMPLE_FRACTION,
                        sep = "_"))  %>%
  select(LAKE_HISTORY_ID,
         SAMPLE_DATE,
         combined,
         RSLT_RESULT_VALUE,
         RSLT_LABORATORY_QUALIFIER,
         RSLT_VALIDATOR_QUALIFIER,
         RSLT_PROFILE_DEPTH) %>%
  mutate(RSLT_RESULT_VALUE=ifelse(!is.na(RSLT_LABORATORY_QUALIFIER)&(RSLT_LABORATORY_QUALIFIER=="U"|RSLT_LABORATORY_QUALIFIER=="UE"),"0",RSLT_RESULT_VALUE),
         RSLT_RESULT_VALUE=as.numeric(RSLT_RESULT_VALUE)) %>%
  filter(!is.na(RSLT_RESULT_VALUE),
         is.na(RSLT_VALIDATOR_QUALIFIER)|(RSLT_VALIDATOR_QUALIFIER!="R"),
         combined %in% c('CHLOROPHYLL A_OW_TOTAL',
                         'PHOSPHORUS, TOTAL_OW_TOTAL',
                         "MICROCYSTIN_OW_NA",
                         "NITROGEN, NITRATE (AS N)_OW_TOTAL",
                         "NITROGEN, NITRATE-NITRITE_OW_TOTAL",
                         "NITROGEN, KJELDAHL, TOTAL_OW_TOTAL",
                         "NITROGEN, TOTAL_OW_TOTAL",
                         "DISSOLVED OXYGEN_DP_NA",
                         "TRUE COLOR_OW_TOTAL",
                         "PH_DP_NA",
                         "SPECIFIC CONDUCTANCE_DP_NA",
                         "TEMPERATURE_DP_NA",
                         "DEPTH, SECCHI DISK DEPTH_SD_NA",
                         "CALCIUM_OW_TOTAL",
                         "CHLORIDE_OW_TOTAL",
                         "CHLOROPHYLL A (PROBE) CONCENTRATION, CHLOROPHYTE (GREEN ALGAE)_OW_NA",
                         "CHLOROPHYLL A (PROBE) CONCENTRATION, CRYPTOPHYTA (CRYPTOPHYTES)_OW_NA",
                         "CHLOROPHYLL A (PROBE) CONCENTRATION, CYANOBACTERIA (BLUEGREEN)_OW_NA",
                         "CHLOROPHYLL A (PROBE) CONCENTRATION, DINOPHYTA (DIATOMS)_OW_NA",
                         "CHLOROPHYLL A (PROBE) CONCENTRATION, TOTAL_OW_NA",
                         "ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL",
                         "ARSENIC_BS_TOTAL",
                         "ARSENIC_OW_TOTAL",
                         "IRON_BS_TOTAL",
                         "IRON_OW_TOTAL",
                         "MAGNESIUM_BS_TOTAL",
                         "MAGNESIUM_OW_TOTAL")) %>%
  select(LAKE_HISTORY_ID,SAMPLE_DATE,combined,RSLT_RESULT_VALUE,RSLT_PROFILE_DEPTH) %>%
  distinct(LAKE_HISTORY_ID,SAMPLE_DATE,combined,RSLT_PROFILE_DEPTH,.keep_all = TRUE) %>%
  rename(LAKE_ID=LAKE_HISTORY_ID,
         chemical_name=combined,
         result_value=RSLT_RESULT_VALUE,
         profile_depth=RSLT_PROFILE_DEPTH)

   # dissolved oxygen:
   # keep DO values between 0 and 2m depth
lab2 <- lab %>% 
   mutate(keep=case_when(
     !(chemical_name=="DISSOLVED OXYGEN_DP_NA") ~ "no",
     chemical_name=="DISSOLVED OXYGEN_DP_NA" & profile_depth <= 2 ~ "yes",
     chemical_name=="DISSOLVED OXYGEN_DP_NA" & profile_depth > 2 ~ "no")) %>%
   filter(keep!="no") %>%
   select(-keep)

# mean DO for each lake each date
DO <- aggregate(lab2$result_value,list(lab2$LAKE_ID,lab2$SAMPLE_DATE),FUN=mean) %>% 
  mutate(chemical_name="DISSOLVED OXYGEN_epi") %>% 
  rename(LAKE_ID=Group.1,
         SAMPLE_DATE=Group.2,
         result_value=x)

#thermocline
thermocline<-lab %>% 
  filter(chemical_name=='TEMPERATURE_DP_NA') %>% 
  mutate(thermocline=NA)
LID<-thermocline$LAKE_ID[1]
date<-thermocline$SAMPLE_DATE[1]
depth<-thermocline$profile_depth[1]
temp<-thermocline$result_value[1]

for(i in seq(nrow(thermocline))){
  current<-thermocline[i,]
  if(current$LAKE_ID==LID&current$SAMPLE_DATE==date){
      depth=current$profile_depth
      if((temp-current$result_value)>1){
        thermocline$thermocline[i]<-current$profile_depth
      }
      temp=current$result_value
  }
  else{
    LID=current$LAKE_ID
    date=current$SAMPLE_DATE
    depth=current$profile_depth
    temp=current$result_value
  }
}

thermocline<-thermocline %>%  #pull the lowest value for all
  group_by(LAKE_ID,SAMPLE_DATE) %>% 
  mutate(thermocline=min(thermocline, na.rm=T)) %>% 
  ungroup() %>% 
  mutate(thermocline=ifelse(thermocline==Inf,NA,thermocline)) %>% 
  select(LAKE_ID,SAMPLE_DATE,thermocline,profile_depth) %>% 
  filter(!is.na(thermocline)) %>%   #remove those without a thermocline
  distinct()

#epilimentic means for ph and spconductance
epi<-lab %>% 
  inner_join(thermocline,by=c('LAKE_ID','SAMPLE_DATE','profile_depth')) %>% 
  filter(chemical_name %in% c("PH_DP_NA","SPECIFIC CONDUCTANCE_DP_NA")) %>% 
  mutate(result_value = ifelse(chemical_name=="PH_DP_NA",(10^result_value),result_value)) %>% 
  distinct() %>% 
  arrange(LAKE_ID,SAMPLE_DATE,chemical_name,profile_depth) 

epi<-epi %>% 
  filter(profile_depth<=thermocline) %>% 
  distinct() %>% 
  group_by(LAKE_ID,SAMPLE_DATE,chemical_name) %>% 
  summarize(Mean=mean(result_value,na.rm=TRUE),
            n=n()) %>% 
  filter(n>2) %>% 
  select(LAKE_ID,SAMPLE_DATE,chemical_name,Mean)

epi<-epi %>% 
  mutate(Mean=ifelse(chemical_name=="PH_DP_NA",log10(Mean),Mean)) %>% 
  rename(result_value=Mean) %>% 
  mutate(chemical_name=case_when(
    chemical_name=="PH_DP_NA"~"PH_epi",
    chemical_name=="SPECIFIC CONDUCTANCE_DP_NA"~"SPECIFIC CONDUCTANCE_epi"
  ))

# read in site data
sites<-read.csv("Probability_Based_Sites_2020_2021.csv")
sites<-sites %>% 
  rename(siteID=SITE_ID,
         xcoord=LON_DD83,
         ycoord=LAT_DD83,
         Eval_Status=EvalStatus) %>% 
  filter(Eval_Status!="") %>%    #removing sites that we haven't yet evaluated
  mutate(Eval_Status=trimws(Eval_Status))

# restrict to only the data in the probability study and spread the data
att<-merge(lab,epi,by=c("LAKE_ID","SAMPLE_DATE","chemical_name"),all=TRUE) %>% 
  mutate(result_value=ifelse(is.na(result_value.x),result_value.y,result_value.x)) %>% 
  select(-result_value.x,-result_value.y)
att<-merge(att,DO,by=c("LAKE_ID","SAMPLE_DATE","chemical_name"),all=TRUE)%>% 
  mutate(result_value=ifelse(is.na(result_value.x),result_value.y,result_value.x)) %>% 
  filter(!chemical_name %in% c("DISSOLVED OXYGEN_DP_NA","PH_DP_NA","SPECIFIC CONDUCTANCE_DP_NA","TEMPERATURE_DP_NA")) %>% 
  select(-result_value.x,-result_value.y)
  
att<-merge(att,sites,by=c('LAKE_ID'),all.y = TRUE) %>% distinct()
att<-att %>% spread(chemical_name,result_value,fill = NA)

att<-att %>% filter((Eval_Status=="Target_Sampled"&!is.na(`CHLOROPHYLL A_OW_TOTAL`)&!is.na(`PHOSPHORUS, TOTAL_OW_TOTAL`)) |
                      (Eval_Status!="Target_Sampled") |
                      (LAKE_ID %in% c("0703UWBXXX1","0801KAY0984A","1203MET0821","0602LUD0099","0801GUL0969")))

#creating thresholds
att<-att %>% 
  # remove fields in the sites table that aren't relevant
  select(-Accessible,-Comments,-Contact,-STATUS) %>%
  # create total nitrogen
  mutate(`NITROGEN, TOTAL`=case_when(
    !is.na(`NITROGEN, KJELDAHL, TOTAL_OW_TOTAL`) ~
      (`NITROGEN, NITRATE-NITRITE_OW_TOTAL`+`NITROGEN, KJELDAHL, TOTAL_OW_TOTAL`),
    is.na(`NITROGEN, KJELDAHL, TOTAL_OW_TOTAL`) ~ `NITROGEN, TOTAL_OW_TOTAL`)) %>%
  # DIN:TP
  mutate(DINTP=`NITROGEN, NITRATE (AS N)_OW_TOTAL`/`PHOSPHORUS, TOTAL_OW_TOTAL`) %>% 
  # trophic status
  mutate(phos_trophic=case_when(
    `PHOSPHORUS, TOTAL_OW_TOTAL`<=0.01 ~ "Oligotrophic",
    between(`PHOSPHORUS, TOTAL_OW_TOTAL`,0.01,0.02) ~ "Mesotrophic",
    `PHOSPHORUS, TOTAL_OW_TOTAL`>=0.02 ~ "Eutrophic")) %>%
  mutate(chla_trophic=case_when(
    `CHLOROPHYLL A_OW_TOTAL`<=2 ~ "Oligotrophic",
    between(`CHLOROPHYLL A_OW_TOTAL`,2,8) ~ "Mesotrophic",
    `CHLOROPHYLL A_OW_TOTAL`>=8 ~ "Eutrophic")) %>%
  # EPA thresholds
  mutate(TP_threshold=case_when(
    `PHOSPHORUS, TOTAL_OW_TOTAL`<=0.016 ~ "Good",
    between(`PHOSPHORUS, TOTAL_OW_TOTAL`, 0.016, 0.0279) ~ "Fair",
    `PHOSPHORUS, TOTAL_OW_TOTAL`>=0.0279 ~ "Poor")) %>%
  mutate(TN_threshold=case_when(
    `NITROGEN, TOTAL`<=0.428 ~ "Good",
    between(`NITROGEN, TOTAL`, 0.428, 0.655) ~ "Fair",
    `NITROGEN, TOTAL`>=0.655 ~ "Poor")) %>%
  mutate(CHLA_threshold=case_when(
    `CHLOROPHYLL A_OW_TOTAL`<=4.52 ~ "Good",
    between(`CHLOROPHYLL A_OW_TOTAL`, 4.52, 8.43) ~ "Fair",
    `CHLOROPHYLL A_OW_TOTAL`>=8.43 ~ "Poor")) %>%
  # microcystin
  mutate(microcystin=case_when(
    is.na(`MICROCYSTIN_OW_NA`) ~"Non-detect",
    `MICROCYSTIN_OW_NA`<8 ~ "Microcystin Detected",
    `MICROCYSTIN_OW_NA`>=8 ~ "Most disturbed")) %>%
  # dissolved oxygen
  mutate(d.oxygen=case_when(
    `DISSOLVED OXYGEN_epi`<=3 ~ "Poor",
    between(`DISSOLVED OXYGEN_epi`, 3, 5) ~ "Fair",
    `DISSOLVED OXYGEN_epi`>=5 ~ "Good")) %>% 
  #nutrient limitation
  mutate(N_LIMIT=case_when(
    `NITROGEN, TOTAL`/`PHOSPHORUS, TOTAL_OW_TOTAL`<=10 ~ "N-limited",
    between(`NITROGEN, TOTAL`/`PHOSPHORUS, TOTAL_OW_TOTAL`, 10, 20) ~ "Co-limited",
    `NITROGEN, TOTAL`/`PHOSPHORUS, TOTAL_OW_TOTAL`>=20 ~ "P-limited")) %>% 
  #secchi
  mutate(secchi=case_when(
    `DEPTH, SECCHI DISK DEPTH_SD_NA`<=2 ~ "Eutrophic",
    between(`DEPTH, SECCHI DISK DEPTH_SD_NA`, 2, 5) ~ "Mesotrophic",
    `DEPTH, SECCHI DISK DEPTH_SD_NA`>=5 ~ "Oligotrophic")) %>% 
  #zebra mussels
  mutate(zebra=case_when(
    CALCIUM_OW_TOTAL<=10 ~ "Not susceptible",
    between(CALCIUM_OW_TOTAL, 10, 20) ~ "May be susceptible",
    CALCIUM_OW_TOTAL>=20 ~ "Highly susceptible")) %>% 
  #cslap
  mutate(conductance=case_when(
    `SPECIFIC CONDUCTANCE_epi`<=125 ~ "Soft",
    between(`SPECIFIC CONDUCTANCE_epi`, 125, 250) ~ "Average",
    `SPECIFIC CONDUCTANCE_epi`>=250 ~ "Hard")) %>%
  mutate(color=case_when(
    `TRUE COLOR_OW_TOTAL`<=10 ~ "Uncolored",
    between(`TRUE COLOR_OW_TOTAL`, 10, 30) ~ "Weak",
    `TRUE COLOR_OW_TOTAL`>=30 ~ "High")) %>% 
  mutate(ph=case_when(
    `PH_epi`<=6.5 ~ "Acidic",
    between(`PH_epi`, 6.5, 7.5) ~ "~Neutral",
    between(`PH_epi`, 7.5, 8.5) ~ "Slightly alk",
    `PH_epi`>=8.5 ~ "Highly alk")) %>% 
  #leech
  mutate(leech=case_when(
    `PHOSPHORUS, TOTAL_OW_TOTAL`<=0.030 & `TRUE COLOR_OW_TOTAL`<=20 ~ "Blue",
    `PHOSPHORUS, TOTAL_OW_TOTAL`>0.030 & `TRUE COLOR_OW_TOTAL`<=20 ~ "Green",
    `PHOSPHORUS, TOTAL_OW_TOTAL`<=0.030 & `TRUE COLOR_OW_TOTAL`>20 ~ "Brown",
    `PHOSPHORUS, TOTAL_OW_TOTAL`>0.030 & `TRUE COLOR_OW_TOTAL`>20 ~ "Murky"
  )) %>% 
  #chlorophyll
  rename(CHLOROPHYTE=`CHLOROPHYLL A (PROBE) CONCENTRATION, CHLOROPHYTE (GREEN ALGAE)_OW_NA`,
         CRYPTOPHYTA=`CHLOROPHYLL A (PROBE) CONCENTRATION, CRYPTOPHYTA (CRYPTOPHYTES)_OW_NA`,
         CYANOBACTERIA=`CHLOROPHYLL A (PROBE) CONCENTRATION, CYANOBACTERIA (BLUEGREEN)_OW_NA`,
         DINOPHYTA=`CHLOROPHYLL A (PROBE) CONCENTRATION, DINOPHYTA (DIATOMS)_OW_NA`,
         PROBE_TOTAL=`CHLOROPHYLL A (PROBE) CONCENTRATION, TOTAL_OW_NA`) %>% 
  mutate(chlorophyte=case_when(
    CHLOROPHYTE/PROBE_TOTAL<=0.25 ~ "Low",
    between(CHLOROPHYTE/PROBE_TOTAL,0.25,0.5) ~ "Medium",
    CHLOROPHYTE/PROBE_TOTAL>=0.5 ~ "High")) %>% 
  mutate(cryptophyta=case_when(
    CRYPTOPHYTA/PROBE_TOTAL<=0.25 ~ "Low",
    between(CRYPTOPHYTA/PROBE_TOTAL,0.25,0.5) ~ "Medium",
    CRYPTOPHYTA/PROBE_TOTAL>=0.5 ~ "High")) %>% 
  mutate(cyanobacteria=case_when(
    CYANOBACTERIA/PROBE_TOTAL<=0.25 ~ "Low",
    between(CYANOBACTERIA/PROBE_TOTAL,0.25,0.5) ~ "Medium",
    CYANOBACTERIA/PROBE_TOTAL>=0.5 ~ "High")) %>% 
  mutate(dinophyta=case_when(
    DINOPHYTA/PROBE_TOTAL<=0.25 ~ "Low",
    between(DINOPHYTA/PROBE_TOTAL,0.25,0.5) ~ "Medium",
    DINOPHYTA/PROBE_TOTAL>=0.5 ~ "High")) %>% 
  #alkalinity
  mutate(alkalinity=case_when(
    `ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL` <= 60 ~ "Soft",
    between(`ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL`,60,120) ~ "Moderately hard",
    between(`ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL`,120,180) ~ "Hard",
    `ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL` >= 180 ~ "Very hard"))

# Create a Target/NonTarget status variable
att<-att %>% 
  mutate(statusTNT="Target",
         statusTNT=ifelse(Eval_Status=="NonTarget","NonTarget",statusTNT))

# remove duplicates (multiple samples of same lake)
att <- att %>%
  mutate(SAMPLE_DATE = ymd(SAMPLE_DATE)) %>% # convert to date
  mutate(month = month(SAMPLE_DATE)) %>% # extract month from date
  group_by(siteID) %>%
  mutate(has_aug = 8 %in% month) %>% # annotate as having date in august
  filter(has_aug & month == 8 |
           !has_aug) %>% # filter only august dates from sites with or all from those without
  slice_max(n = 1,
            order_by = SAMPLE_DATE,
            with_ties = F) %>% # change with_ties to TRUE to discard NA values
  select(-has_aug)

att<-att %>% 
  ungroup() %>% 
  mutate(WgtAdj=case_when(
         PROB_CAT=="(1,4]"~(1828/29),
         PROB_CAT=="(4,10]"~(2490/15),
         PROB_CAT=="(10,20]"~(1003/18),
         PROB_CAT=="(20,50]"~(616/20),
         PROB_CAT==">50"~(500/33)))

rm(list=setdiff(ls(), c('newdata',"att","sites")))
```


# 1. Categorical

```{r cat analysis, fig.dim = c(8,8)}

#list variables you are interested in and defined above
trophic <- c("phos_trophic","chla_trophic","N_LIMIT","secchi","leech","color")
minerals <- c("zebra","alkalinity")
in.situ <- c("ph","conductance")
habs <- c("microcystin","chlorophyte","cryptophyta","cyanobacteria","dinophyta")

vars.list <- list(Trophic=trophic,Minerals=minerals,`In Situ`=in.situ,HABs=habs)

n<-0

#analysis
for(i in vars.list){
  
  n<-n+1
  
  CatExtent <- cat_analysis(
    dframe=att,
    vars=i, 
    subpops = , #for example could separate by area category or year
    siteID = "siteID",
    weight = "WgtAdj", #name will probably change in future
    xcoord = "xcoord",
    ycoord = "ycoord")
  
  table <- CatExtent %>% 
    select(Indicator,
           Category,
           Estimate.P,
           LCB95Pct.P,
           UCB95Pct.P) %>% 
    filter(Category!="Total") %>% 
    mutate(Category=factor(Category, levels=c("Poor","Fair","Good",
                                              "Blue","Green","Brown","Murky",
                                              "High","Weak","Uncolored",
                                              "Medium","Low",
                                              "Acidic","~Neutral","Slightly alk","Highly alk",
                                              "Soft","Moderately hard","Average","Hard","Very hard",
                                              "Highly susceptible","May be susceptible","Not susceptible",
                                              "Eutrophic","Mesotrophic","Oligotrophic",
                                              "N-limited","Co-limited","P-limited",
                                              "Non-detect","Microcystin detected","Most disturbed")),
           Indicator=case_when(
             Indicator=="phos_trophic"~"Phosphorus", 
             Indicator=="chla_trophic"~"Chlorophyll-a", 
             Indicator=="TP_threshold"~"Total phosphorus", 
             Indicator=="TN_threshold"~"Total nitrogen", 
             Indicator=="CHLA_threshold"~"Total chlorophyll", 
             Indicator=="microcystin"~"Microcystin",
             Indicator=="d.oxygen"~"Dissolved oxygen",
             Indicator=="N_LIMIT"~"Nutrient limitation", 
             Indicator=="secchi"~"Secchi", 
             Indicator=="zebra"~"Zebra mussel susceptibility", 
             Indicator=="conductance"~"Conductance", 
             Indicator=="color"~"Color", 
             Indicator=="ph"~"pH", 
             Indicator=="leech"~"Nutrient-color status", 
             Indicator=='alkalinity'~"Alkalinity",
             Indicator=="chlorophyte"~"% Chlorophyte",
             Indicator=="cryptophyta"~"% Cryptophyta",
             Indicator=="cyanobacteria"~"% Cyanobacteria",
             Indicator=="dinophyta"~"% Dinophyta",
             Indicator=TRUE~Indicator)
    )
  
  plot<-ggplot(table,aes(x=Category,y=Estimate.P)) +
    geom_col()+
    geom_errorbar(aes(ymin=LCB95Pct.P,ymax=UCB95Pct.P),width=0.2)+
    theme(legend.position = "none")+
    facet_wrap(.~Indicator,scales = "free")+
    ylim(0,100)+
    # scale_x_discrete(guide = guide_axis(n.dodge = 2))+
    labs(y="Percent of Total",x="Condition category",title=paste(names(vars.list)[n],"Parameters"))+
    theme(axis.text.x = element_text(angle = 45,vjust = 1, hjust=1))
  
  plot <- set_panel_size(p = plot, width = unit(4, "cm"), height = unit(4,"cm"))
  
  gridExtra::grid.arrange(plot)
  
}

```

# 2. Continuous

``` {r cont analysis, fig.dim = c(8,8)}

att <- att %>% rename("CHLOROPHYLL_ug_L"=`CHLOROPHYLL A_OW_TOTAL`,
                      "NITROGEN_mg_L"=`NITROGEN, TOTAL`,
                      "PHOSPHORUS_mg_L"=`PHOSPHORUS, TOTAL_OW_TOTAL`,
                      "DISSOLVED_OXYGEN_mg_L"=`DISSOLVED OXYGEN_epi`,
                      "ALKALINITY_mg_L"=`ALKALINITY, TOTAL (AS CACO3)_OW_TOTAL`,
                      "CHLORIDE_mg_L"=CHLORIDE_OW_TOTAL,
                      "CALCIUM_mg_L"=CALCIUM_OW_TOTAL,
                      "SECCHI_m"=`DEPTH, SECCHI DISK DEPTH_SD_NA`,
                      "TRUE_COLOR"=`TRUE COLOR_OW_TOTAL`,
                      "SPEC_CONDUCTANCE"=`SPECIFIC CONDUCTANCE_epi`
                      )

vars <- c("CHLOROPHYLL_ug_L","NITROGEN_mg_L","PHOSPHORUS_mg_L","DISSOLVED_OXYGEN_mg_L","CHLORIDE_mg_L","CALCIUM_mg_L","ALKALINITY_mg_L")

#Creates 3 estimations in list: CDF, percentiles, means.
analysis <- cont_analysis(
  dframe = att,
  vars = vars,
  subpops = ,
  siteID = "siteID",
  weight = "WgtAdj",
  xcoord = "xcoord",
  ycoord = "ycoord")

myvars <- c("CHLOROPHYLL_ug_L","NITROGEN_mg_L","PHOSPHORUS_ug_L","CHLORIDE_mg_L","DISSOLVED_OXYGEN_mg_L")

NY<-analysis$CDF %>% 
  select(Indicator,Value,Estimate.P,LCB95Pct.P,UCB95Pct.P) %>% 
  mutate(Study="NY") %>% 
  mutate(Value=case_when(
    Indicator=="PHOSPHORUS_mg_L"~as.numeric(Value)*1000,
    Indicator=TRUE~as.numeric(Value)
  )) %>% 
  mutate(Indicator=case_when(
    Indicator=="PHOSPHORUS_mg_L"~"PHOSPHORUS_ug_L",
    Indicator=TRUE~Indicator
  )) %>% 
 filter(Indicator %in% c(myvars))

#list variables you are interested in and defined above
trophic <- c("CHLOROPHYLL_ug_L",
             "NITROGEN_mg_L",
             "PHOSPHORUS_mg_L",
             "SECCHI_m",
             "TRUE_COLOR")
minerals <- c("CALCIUM_mg_L","ALKALINITY_mg_L")
salt <- c("CHLORIDE_mg_L")
in.situ <- c("DISSOLVED_OXYGEN_mg_L",
             "PH_epi",
             "SPEC_CONDUCTANCE")
metals <- c("ARSENIC_BS_TOTAL",
            "ARSENIC_OW_TOTAL",
            "IRON_BS_TOTAL",
            "IRON_OW_TOTAL",
            "MAGNESIUM_BS_TOTAL",
            "MAGNESIUM_OW_TOTAL")

vars.list <- list(Trophic=trophic,Minerals=minerals,Salt=salt,`In Situ`=in.situ,Metals=metals)

n<-0

for(i in vars.list){
  
  n<-n+1
  
  #Creates 3 estimations in list: CDF, percentiles, means.
  analysis <- cont_analysis(
    dframe = att,
    vars = i,
    subpops = ,
    siteID = "siteID",
    weight = "WgtAdj",
    xcoord = "xcoord",
    ycoord = "ycoord")
  
  table<-analysis$CDF %>% 
    select(Indicator,Value,Estimate.P,LCB95Pct.P,UCB95Pct.P) %>% 
    filter(Indicator %in% i) %>% 
    mutate(Indicator=case_when(
      Indicator=="CHLOROPHYLL_ug_L"~"Chlorophyll-a (ug/L)",
      Indicator=="NITROGEN_mg_L"~"Total nitrogen (mg/L)",
      Indicator=="PHOSPHORUS_mg_L"~"Total phosphorus (mg/L)",
      Indicator=="DISSOLVED_OXYGEN_mg_L"~"Dissolved oxygen (mg/L)",
      Indicator=="ALKALINITY_mg_L"~"Alkalinity (mg/L)",
      Indicator=="CHLORIDE_mg_L"~"Chloride (mg/L)",
      Indicator=="CALCIUM_mg_L"~"Calcium (mg/L)",
      Indicator=="SECCHI_m"~"Secchi disk depth (m)",
      Indicator=="TRUE_COLOR"~"True color (PCU)",
      Indicator=="SPEC_CONDUCTANCE"~"Conductance (mS/cm)",
      Indicator=="PH_epi"~"pH (SU)",
      Indicator=="ARSENIC_BS_TOTAL"~"Arsenic, bottom (ug/L)",
      Indicator=="ARSENIC_OW_TOTAL"~"Arsenic, open water (ug/L)",
      Indicator=="IRON_BS_TOTAL"~"Iron, bottom (ug/L)",
      Indicator=="IRON_OW_TOTAL"~"Iron, open water (ug/L)",
      Indicator=="MAGNESIUM_BS_TOTAL"~"Magnesium, bottom (ug/L)",
      Indicator=="MAGNESIUM_OW_TOTAL"~"Magnesium, open water (ug/L)",
      Indicator=TRUE~Indicator
    )) %>% 
    mutate(Lower=case_when(
      Indicator=="Chlorophyll-a (ug/L)"~2,
      Indicator=="Total phosphorus (mg/L)"~0.01,
      Indicator=="Specific conductance (mS/cm)"~125,
      Indicator=="Alkalinity (mg/L)"~60,
      Indicator=="Calcium (mg/L)"~10,
      Indicator=="True color (PCU)"~10,
      Indicator=="Secchi disk depth (m)"~2,
      Indicator=TRUE~-5)) %>% 
    mutate(Upper=case_when(
      Indicator=="Chlorophyll-a (ug/L)"~8,
      Indicator=="Total phosphorus (mg/L)"~0.02,
      Indicator=="Specific conductance (mS/cm)"~250,
      Indicator=="Alkalinity (mg/L)"~120,
      Indicator=="Calcium (mg/L)"~20,
      Indicator=="True color (PCU)"~20,
      Indicator=="Secchi disk depth (m)"~5,
      Indicator=TRUE~-5))
  
  plot<-ggplot(table,aes(x=Value,y=Estimate.P,ymin=LCB95Pct.P,ymax=UCB95Pct.P))+
    geom_line()+
    geom_point()+
    geom_ribbon(alpha=0.5)+
    ylim(0,100)+
    scale_x_continuous(limits = c(0, NA))+
    guides(fill="none",shape="none")+
    facet_wrap(.~Indicator, scales="free")+
    geom_vline(aes(xintercept=Lower),linetype="dashed")+
    geom_vline(aes(xintercept=Upper),linetype="dashed")+
    labs(y="Percent of lakes",title=paste(names(vars.list[n]),"Parameters"))

  plot <- set_panel_size(p = plot, width = unit(4, "cm"), height = unit(4,"cm"))
  
  gridExtra::grid.arrange(plot)
  
}

```
