# Program:  NYSAnalysis_lakes.R
# Purpose: statewide analysis
# Programmer: Tony Olsen / Alene Onion
# Date: January 5, 2020

################################################################################################################
#reading in and formatting raw data
################################################################################################################

library(tidyverse)

#raw data
lab<-read.csv("LCI.2020.qaqcd-2020-11.30_with_lakeID.csv")
sites<-read.csv("Probability_Based_Sites_2020.csv")
#no habs - none of the probability sites had any detectable level of microcystin so I added it as a 0 value at the end

#modify the data so it can be merged
lab<-lab %>% 
  mutate(sys_sample_code=substr(sys_sample_code,nchar(sys_sample_code),nchar(sys_sample_code))) %>% 
  filter(sys_sample_code!=2) %>% 
  mutate(chemical_name=paste(chemical_name,result_unit,sep="_"),
         #converting non-detects to 0
         result_value=ifelse(validator_qualifiers=="U",0,result_value)) %>% 
  select(LAKE,chemical_name,result_value) %>% 
  rename(LAKE_ID=LAKE)
sites<-sites %>% 
  rename(siteID=SITE_ID,
         xcoord=LON_DD83,
         ycoord=LAT_DD83,
         Eval_Status=EvalStatus) %>% 
  #removing sites that we haven't yet evaluated
  filter(Eval_Status!="") %>% 
  mutate(Eval_Status=trimws(Eval_Status),
         #the following sites were not sampled although we intended to EXCEPT canandaigua
         #NOTE - we need to add canandaigua data once it is generated by cslap
         Eval_Status=ifelse(LAKE_ID %in% c('0704CAN0286','0903UWBXXX1','1104PAR0432','1301PET0161G'),'Target_NoOwnerAccess',Eval_Status)) 

#now restrict to only the data in the probability study and spread the data
att<-merge(sites,lab,by=c('LAKE_ID'),all.x = TRUE)
att<-att %>% spread(chemical_name,result_value,fill = NA) %>% 
  #adding microcystin results
  mutate(`microcystin_ug/L` =0) %>% 
  #removing an NA column
  select(-`<NA>`) 

#selecting only trophic parameters and adding trophic status
att<-att %>% 
  #removing parameters that aren't trophic parameters
  #we will process these later once we understand the analysis
  select(-`Arsenic_ug/l`,-`Calcium_ug/l`,-`Carbon, Dissolved Organic (DOC)_mg/l`,-`CHLORIDE (AS CL)_mg/l`,
         -`Color, True_color unit`,-`HARDNESS (AS CACO3)_mg/l`,-`Iron_ug/l`,-`Manganese_ug/l`,
         -`Nitrate+Nitrite as Nitrogen_mg/l`,-`Nitrogen, ammonia (As N)_mg/l`,
         -`NITROGEN, KJELDAHL, TOTAL_mg/l`,-`NITROGEN, NITRATE (AS N)_mg/l`,-`NITROGEN, NITRITE_mg/l`,
         -`pH of Color Analysis_pH units`,-`PHOSPHORUS, DISSOLVED (AS P)_mg/l`,
         -`SULFATE (AS SO4)_mg/l`,-`TOTAL ORGANIC CARBON_mg/l`,
         -`microcystin_ug/L`,-`UV 254_1/cm`,-`ALKALINITY, TOTAL (AS CaCO3)_mg/l`) %>% 
  #remove fields in the sites table that aren't relevant
  select(-Accessible,-Comments,-Contact,-X,-STATUS) %>% 
  mutate(phos_trophic="oligotrophic",
         phos_trophic=ifelse(`PHOSPHORUS, TOTAL (AS P)_mg/l`>0.01,"mesotrophic",phos_trophic),
         phos_trophic=ifelse(`PHOSPHORUS, TOTAL (AS P)_mg/l`>0.02,"eutrophic",phos_trophic),
         chla_trophic="oligotrophic",
         chla_trophic=ifelse(`Chlorophyll A_ug/l`>2,"mesotrophic",chla_trophic),
         chla_trophic=ifelse(`Chlorophyll A_ug/l`>8,"eutrophic",chla_trophic))
         #will have to add after we finalize the field data. These data are not yet available
         #secchi_trophic="oligotrophic",
         #secchi_trophic=ifelse(Result.Value>2,"mesotrophic",secchi_trophic),
         #secchi_trophic=ifelse(Result.Value>5,"eutrophic",secchi_trophic)) 


rm(list=setdiff(ls(), c("att")))

################################################################################################################
#The start of the NYSAnalysis code from Tony Olsen
################################################################################################################

#PLease note that these were the criteria for selecting the target population
#the probabilty sites were restricted to waterbodies in the NHD classified as LakePond which includes reservoirs. 
#restricted to those above 6.5 acres, 
#within the boundaries of NYS, 
#we further excluded wetlands by examining satellite imagery and removing sites that are more than 50% covered by macrophytes

head(att)

# look at status variable
summary(att$Eval_Status)
# Create a Target/NonTarget status variable
att<-att %>% 
  mutate(statusTNT="Target",
         statusTNT=ifelse(Eval_Status=="NonTarget","NonTarget",statusTNT))

addmargins(table(att$Eval_Status,att$statusTNT))

################################################################################################################
#I presumed that the wgt categories should be a simple division of the number in each category divided by the total
#the first chunk of code I presume 
################################################################################################################
#calculating weights for each strata
#these initial weights are based on the total frame size
att<-att %>% 
  mutate(wgt=NA,
         wgt=ifelse(PROB_CAT=="(1,4]",17/6437,wgt),
         wgt=ifelse(PROB_CAT=="(4,10]",2490/6437,wgt),
         wgt=ifelse(PROB_CAT=="(10,20]",1003/6437,wgt),
         wgt=ifelse(PROB_CAT=="(20,50]",616/6437,wgt),
         wgt=ifelse(PROB_CAT==">50",500/6437,wgt),)

# Adjust sample weights to account for use of oversample sites
sum(att$wgt)
framesize_LC <- c("New York State"=68)

#for some strange reason this code didn't work for me so I calculated it maually below
#library(spsurvey)
#att$WgtAdj <- adjwgt(rep(TRUE, nrow(att)), att$wgt, att$PROB_CAT, framesize_LC)

#the equation for adjusted weight is initial weight * framesize/sum(initial weights)
#first calculate the sum of initial weights
initial<-att %>% 
  select(PROB_CAT,wgt) %>% distinct() %>% 
  mutate(WgtAdj=NA,
         WgtAdj=ifelse(PROB_CAT=="(1,4]",17*wgt,WgtAdj),
         WgtAdj=ifelse(PROB_CAT=="(4,10]",2490*wgt,WgtAdj),
         WgtAdj=ifelse(PROB_CAT=="(10,20]",1003*wgt,WgtAdj),
         WgtAdj=ifelse(PROB_CAT=="(20,50]",616*wgt,WgtAdj),
         WgtAdj=ifelse(PROB_CAT==">50",500*wgt,WgtAdj))
initial<-sum(initial$WgtAdj)
att<-att %>% 
  mutate(WgtAdj=wgt*(68/initial))

sum(att$WgtAdj)

# Estimate TNT extent
sites <- data.frame(siteID=att$siteID, Use=rep(TRUE, nrow(att)))
subpop <- data.frame(siteID=att$siteID,
                     PROB_CAT=att$PROB_CAT)
design <- data.frame(siteID=att$siteID,
                     wgt=att$WgtAdj,
                     xcoord=att$xcoord,
                     ycoord=att$ycoord)
dataTNT <- data.frame(siteID=att$siteID, StatusTNT=att$statusTNT)
TNTextent <- cat.analysis(sites, subpop, design, dataTNT,
                          popsize=list(PROB_CAT=framesize_LC))
TNTextent

# Estimate Target extent reasons
sites <- data.frame(siteID=att$siteID, Use=att$statusTNT == "Target")
dataTarget <- data.frame(siteID=att$siteID, TargetReason=att$Eval_Status)
TargetExtent <- cat.analysis(sites, subpop, design, dataTarget)
TargetExtent

#  Estimate assessment result
sites <- data.frame(siteID=att$siteID, Use=att$Eval_Status == "Target_Sampled")
datacat <- data.frame(siteID=att$siteID, 
                      phos_Trophic=att$phos_trophic,
                      chla_trophic=att$chla_trophic)
CatExtent <- cat.analysis(sites, subpop, design, datacat)
CatExtent


# Estimate continuous variables cdf
sites <- data.frame(siteID=att$siteID, Use=att$statusTNT == "Target")
datacont <- data.frame(siteID=att$siteID,
                       phosphorus=att$`PHOSPHORUS, TOTAL (AS P)_mg/l`,
                       chlorophyll=att$`Chlorophyll A_ug/l`)
Cont_Est <- cont.analysis(sites, subpop, design, datacont)

cont.cdfplot("NYS_Cont_Data_CDF_Estimates.pdf", Cont_Est$CDF,
             cdf.page=1, height=6, width=6, ylbl.r="Lakes")

comb <- rbind(TNTextent, TargetExtent, CatExtent)
row.names(comb)  <- 1:nrow(comb)
write.table(comb, file="NYS.Probability.Sampling.csv", sep=",", col.names=NA)
write.table(Cont_Est$CDF, file="NYS.Probability.Sampling CDF Estimates.csv",
            sep=",", col.names=NA)
write.table(Cont_Est$Pct, file="NYS.Probability.Sampling PCT Estimates.csv",
            sep=",", col.names=NA)            


